//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace EF.GenericRepository.Entity
{
    
    
    [Serializable]
    public partial class Level : EntityBase<int>
    {
        #region Primitive Properties
    
        public override int Id
        {
            get;
            set;
        }
                
        public virtual string Name
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Log> Logs
        {
            get
            {
                if (_logs == null)
                {
                    var newCollection = new FixupCollection<Log>();
                    newCollection.CollectionChanged += FixupLogs;
                    _logs = newCollection;
                }
                return _logs;
            }
            set
            {
                if (!ReferenceEquals(_logs, value))
                {
                    var previousValue = _logs as FixupCollection<Log>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLogs;
                    }
                    _logs = value;
                    var newValue = value as FixupCollection<Log>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLogs;
                    }
                }
            }
        }
        private ICollection<Log> _logs;

        #endregion

        #region Association Fixup
    
        private void FixupLogs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Log item in e.NewItems)
                {
                    item.Level = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Log item in e.OldItems)
                {
                    if (ReferenceEquals(item.Level, this))
                    {
                        item.Level = null;
                    }
                }
            }
        }

        #endregion

    }
}
